# Generated by Django 5.2.3 on 2025-06-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_pay_options_pay_link_pay_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pay",
            name="form_of_payment",
            field=models.CharField(
                blank=True,
                choices=[("Наличные", "Наличные"), ("Перевод на счет", "Перевод")],
                help_text="Выберите способ оплаты",
                max_length=15,
                null=True,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
