# Generated by Django 5.2.3 on 2025-06-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_pay_form_of_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="pay",
            name="payment_status",
            field=models.CharField(
                blank=True,
                default="unpaid",
                help_text="Укажите статус оплаты",
                max_length=20,
                null=True,
                verbose_name="Статус оплаты",
            ),
        ),
    ]
