# Generated by Django 5.2.3 on 2025-06-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_alter_lesson_course_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={"verbose_name": "Подписка", "verbose_name_plural": "Подписки"},
        ),
    ]
