# Generated by Django 5.2.3 on 2025-07-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_alter_subscription_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="update_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата обновления курса"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="update_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата обновления урока"
            ),
        ),
    ]
