# Generated by Django 5.2.3 on 2025-07-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_course_notification_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="notification_task_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="id задачи уведомления",
            ),
        ),
    ]
